apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: otel-collector
    app.kubernetes.io/name: opentelemetry-collector
    app.kubernetes.io/version: 0.98.0
  name:  otel-collector-nodes-opentelemetry-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name:  otel-collector-nodes-opentelemetry-collector
subjects:
- kind: ServiceAccount
  name:  otel-collector-nodes-opentelemetry-collector
  namespace: otel