apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: otel-collector
    app.kubernetes.io/name: opentelemetry-collector
    app.kubernetes.io/version: 0.96.0
  name: otel-collector-opentelemetry-collector
  namespace: otel
data:
  relay: |
    exporters:
      debug: {}
      otlp/auth:
        endpoint: "https://192.168.0.106:4317"
        tls:
          insecure: false
          insecure_skip_verify: true
        auth:
          authenticator: basicauth/client
    extensions:
      health_check:
        endpoint: ${env:MY_POD_IP}:13133
      basicauth/client:
        client_auth:
          username: myuser
          password: mypassword
    processors:
      batch: {}
      memory_limiter:
        check_interval: 5s
        limit_percentage: 80
        spike_limit_percentage: 25
    receivers:
      k8s_cluster:
        collection_interval: 10s
      k8sobjects:
        objects:
        - exclude_watch_type:
          - DELETED
          group: events.k8s.io
          mode: watch
          name: events
      otlp:
        protocols:
          http:
            endpoint: ${env:MY_POD_IP}:4318
            cors:
              allowed_origins: ["*"]
            tls:
              cert_file: /certs/tls.crt
              key_file: /certs/tls.key
          grpc:
            endpoint: ${env:MY_POD_IP}:4317
            tls:
              cert_file: /certs/tls.crt
              key_file: /certs/tls.key
    service:
      extensions:
      - health_check
      - basicauth/client
      pipelines:
        logs:
          exporters:
          - debug
          - otlp/auth
          processors:
          - memory_limiter
          - batch
          receivers:
          - otlp
          - k8sobjects
        metrics:
          exporters:
          - debug
          - otlp/auth
          processors:
          - memory_limiter
          - batch
          receivers:
          - otlp
          - k8s_cluster
        traces:
          exporters:
          - debug
          - otlp/auth
          processors:
          - memory_limiter
          - batch
          receivers:
          - otlp
      telemetry:
        metrics:
          address: ${env:MY_POD_IP}:8888
