apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: otel
  labels:
    app: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s
      scrape_timeout: 10s

    scrape_configs:
      - job_name: prometheus-otel
        metrics_path: /metrics
        static_configs:
          - targets:
              - 'otel-collector-opentelemetry-collector:8080'