apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: otel-collector-nodes
    app.kubernetes.io/name: opentelemetry-collector
    app.kubernetes.io/version: 0.98.0
  name: otel-collector-nodes-opentelemetry-collector
  namespace: otel
