apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: otel
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - image: quay.io/prometheus/prometheus:v2.52.0
          name: prometheus
          args: ["--storage.tsdb.path=/prometheus", "--config.file=/etc/prometheus/prometheus.yml"]
          volumeMounts:
            - mountPath: /prometheus
              name: prometheus-data
            - mountPath: /etc/prometheus/prometheus.yml
              name: prometheus-config
              subPath: prometheus.yml
      volumes:
        - name: prometheus-data
          persistentVolumeClaim:
            claimName: prometheus-data
        - name: prometheus-config
          configMap:
            name: prometheus-config